version: '3'

services:
  nodejs:
    build:
      context: .
    image: skeleton_nodejs_image
    container_name: skeleton_nodejs
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    env_file:
      - ./.env
    volumes:
      - ./:/app
    networks:
      - default

networks:
  default:
    driver: bridge
